[project]
name = 'IoT_Device_Registry_and_Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.IoT_Device_Registry_and_Management]
path = 'contracts/IoT_Device_Registry_and_Management.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
